# Site
repository: suvambh/suvambh.github.io
favicon: images/favicon.ico


#basePath: /_site
# Content configuration version
version: 2

# Personal info
name: Suvam Bhattacharya
title: Engineer and researcher
email: suvam.quantum.1@gmail.com
website: https://github.com/suvambh

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: facespics
github_username:  suvambh
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Suvam. 
  I recently finished a Ph.D. in Quantum Physics and now I am coding all day for no reason!
  This resulted in me getting skilled at : <mark>python</mark> <mark>statistical learning</mark> and  <mark>algorithms</mark> 

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: This website
        link: github.com/suvambh/CV
        # link_text: Project Website
        additional_links:
          - title:  suvambh/CV
            icon: fab fa-github
            url: github.com/suvambh/CV
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Cloning and Modification of Github projects in foreign languages
        description: | # this will include new lines to allow paragraphs
          I started tweaking this project as a way of learning <mark>Ruby</mark> and <mark>Jekyll</mark>

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Laboratoire de Physique des Solides, Université Paris-Saclay
        link: https://www.lps.u-psud.fr/en/home-english/
        link_text: Website
        sub_title: Ph.D. student
        caption: October 2018 - December 2021
        quote: >
          Experimental and numerical modelling of the mysterious <mark>quantum spin liquid</mark> state of matter.
        description: | # this will include new lines to allow paragraphs
          Investigation of the Quantum Spin Liquid state. 
          The rise of quantum materials observed in the past decades has been a source of great excitement for scientists and engineers, with the flourishing of new concepts and electronic phases of matter. 
          These new quantum phases are of fundamental importance given the promise they hold for future technological advancements. 
          My personal motivation was to gain a better understanding of the nature of the physical reality by exploring these 'weird' states of matter. 
          As we are figuring out now, these phases of matter goes against all common intuitions and hold the possibility to display a range of exciting exotic physics.
          My research included experimentation with quantum spin liquid candidate materials coupled with theoretical development, modelling and simulations.

  
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: Ecole Polytechnique
        caption: 2014 - 2018
        sub_title: Ingineur Polytechnicien 
        quote: >
          Established in 1794, Polytechnique is one of the oldest engineering institution in the World, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading institute in not just France but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Polytechnique I learnt most of my key skills that have I have taken through my career such as foundational mathematics, problem solving strategies and team work. 
        layout: bottom
        title: Ecole Polytechnique
        caption: 2014 - 2018
        sub_title: Ingineur Polytechnicien 
        quote: >
          Established in 1794, Polytechnique is one of the oldest engineering institution in the World, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading institute in not just France but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Polytechnique I learnt most of my key skills that have I have taken through my career such as foundational mathematics, problem solving strategies and team work. 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Guitar
      - Cycling
      - Sports
      

      Look at this cool image  
      ![Corsica](/images/corsica.JPG "Corsica")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
